### ISSUE TITLE
Missing Python 3.2 support

### ISSUE THREAD

**Issue by pyghassen** [gregmuellegger/django-floppyforms#135]
I was trying to install floppyforms using python 3.2.3, without success.

**Comment by gregmuellegger** [comment]
Thanks for report! We didn't test against Python 3.2 so far. Now the CI Server also runs tests against Python 3.2 and Python 3.4. See here: https://travis-ci.org/gregmuellegger/django-floppyforms

**Comment by gregmuellegger** [comment]
django-floppyforms 1.4.0 is now available on PyPI which includes these changes. Thanks for the report!
https://pypi.python.org/pypi/django-floppyforms/
