### ISSUE TITLE
Docs changelog is vastly out of date

### ISSUE THREAD

**Issue by SmileyChris** [gregmuellegger/django-floppyforms#139]
It'd be nice to have a summary of the changes in recent versions in the docs as well as the `CHANGES.rst` -- *1.1.1 (2014-01-21)* is the last recorded change in `docs/index.rst`

**Comment by gregmuellegger** [comment]
Yes, good idea. I always missed to update the changelog in the docs since I have taken over the maintenance. I will adjust the docs to use the same sourcefile as the changelog file in the root of the respository.

**Comment by gregmuellegger** [comment]
Fixed as with 5ec2dcf30ed4c202ea82063122e06d5f42ff3a30.
See: http://django-floppyforms.readthedocs.org/en/latest/changelog.html
