### ISSUE TITLE
Import Warning Django 1.8

### ISSUE THREAD

**Issue by lzanuz** [gregmuellegger/django-floppyforms#147]
RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.

django.forms.util will be removed on 1.9.

**Comment by gregmuellegger** [comment]
True thing, I will have a look at this. Thanks for the report! If you want to give it a shot in the meantime, then feel free to create a pull request for this. Go and ask me any questions you have along the way!

**Comment by rnevius** [comment]
This was already patched with commit 399b6b4

**Comment by melinath** [comment]
Yep, looks like a patch to fix this was already merged into master.

**Comment by lzanuz** [comment]
OK, I'm using django-floppyforms==1.3.0.

Maybe it's time of a new version.

Thanks.

**Comment by gregmuellegger** [comment]
I just released django-floppyforms 1.4.0 which contains the fix for this. Thanks for your help!
https://pypi.python.org/pypi/django-floppyforms/

**Comment by rnevius** [comment]
Thanks @gregmuellegger :+1:

**Comment by lzanuz** [comment]
+1
