### ISSUE TITLE
floppy forms should display the label_suffix set by user

### ISSUE THREAD

**Issue by subramanyamVemu** [gregmuellegger/django-floppyforms#148]
If the form is instantiated with label_suffix, then floppy forms should display the same

Right now it always display ":"

Thanks
Subramanyam

**Comment by gregmuellegger** [comment]
Yes, I absolutely agree. That should be a fairly small change in the `templates/floppyforms/rows/*` templates. However we would need at least a small bit of testing for this.

Would you like to contribute to make this happen? I'm happy to review and merge any pull requests or help out if you have questions about how to get started.

**Comment by subramanyamVemu** [comment]
Sure I will go through the code over the weekend 

Thanks
Subramanyam

**Comment by gregmuellegger** [comment]
Super! Feel free to ask anything if you get stuck somewhere.

**Comment by subramanyamVemu** [comment]
Gone through the code but a little stuck on the how to set the label_suffix as the BaseForm attribute 

Also in 1.8 even the form fields can have a different label_suffix than the form itself

**Comment by gregmuellegger** [comment]
Sorry, I forgot to respond to your questions :(

I implemented the feature now as an apology. You can find support for `label_suffix` (in forms and  fields) in master for the builtin layouts.

Does it work for you now as expected?

**Comment by gregmuellegger** [comment]
I just release django-floppyforms 1.5.0 which includes the changes for this ticket. Happy coding.
