### ISSUE TITLE
local copy of openlayers.js

### ISSUE THREAD

**Issue by ouhouhsami** [gregmuellegger/django-floppyforms#15]
hello, 

May be it's no relevant, but I would like to have a local copy of openlayers, and google (js and css) instead of getting them via their absolute URL.
- how can I achieve this ? (we could have sort of settings for that, instead of modify the widget Media class of BaseGMapWidget BaseOsmWidget or BaseMetacartaWidget)
- how interesting is it to use, for example django_compressor, to increase performance ?

thx

**Comment by galuszkak** [comment]
Good Job @gregmuellegger  :+1:

**Comment by gregmuellegger** [comment]
Took a few years but finally it for good ;)
Am 17.02.2015 00:31 schrieb "Kamil Gałuszka" <notifications@github.com>:

**Comment by gregmuellegger** [comment]
django-floppyforms 1.4.0 is now available on PyPI which includes these changes. Thanks for the help!
https://pypi.python.org/pypi/django-floppyforms/

**Comment by mikeedwards** [comment]
Hi! It looks like some of the OpenLayers static files didn't make it to PyPi. For example the `theme/default/` directory is missing.

**Comment by gregmuellegger** [comment]
@mikeedwards Doh! You are absolutely right. I added them to the source distribution now and released 1.4.1 which includes these. Thanks for letting me know.

**Comment by mikeedwards** [comment]
Awesome! Thank you for fixing that so quickly--totally made my morning!
