### ISSUE TITLE
Import Warning Django 1.8

### ISSUE THREAD

**Issue by lzanuz** [gregmuellegger/django-floppyforms#152]
RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.

**Comment by melinath** [comment]
This was resolved on master as of April 2, 2015. See #147... which it looks like you also opened? Are you saying you're still seeing this error using floppyforms 1.4.0?

**Comment by lzanuz** [comment]
I'm using django-floppyforms==1.4.1

With a grep on source I found this:

widgets.py:    from django.forms.util import to_current_timezone
templatetags/floppyforms.py:    from django.forms.util import ErrorList

If this is corrected on master, maybe is time of a new revision for pip.

Thanks

**Comment by lzanuz** [comment]
Yes, sorry,

Was cached in a pyc file on virtualenv.
