### ISSUE TITLE
Allow formconfig with non-inline layouts

### ISSUE THREAD

**Issue by jwpeddle** [gregmuellegger/django-floppyforms#155]
As far as I can tell, there's currently no way to provide formconfig template tags without using an inline layout. It would be convenient to be able to otherwise use a layout template but provide row/field overrides.

Something like:
```html
{% form myform using "floppyforms/layouts/default.html" %}
    {% formconfig field with placeholder="Foobar" for form.field1 %}
{% endform %}
```
This way you don't have to decide between all-or-nothing for layouts.

**Comment by gregmuellegger** [comment]
You could use this:

```
{% form myform using %}
    {% formconfig field with placeholder="Foobar" for form.field1 %}
    {% form form using "floppyforms/layouts/default.html" %}
{% endform %}
```

The other option is to create a new formlayout like:

**`my_layout.html`**
```
{% extends "floppyforms/layouts/default.html" %}
{% load floppyforms %}

{% block formconfig %}
    {% formconfig field with placeholder="Foobar" for form.field1 %}
{% endblock %}
```

Hope this helps :)

**Comment by jwpeddle** [comment]
Weird, I could have sworn I tried that first solution to no avail, but it does appear to work. Thanks!
