### ISSUE TITLE
DateInput ignores format kwarg

### ISSUE THREAD

**Issue by orestis** [gregmuellegger/django-floppyforms#164]
Should be pretty obvious:    

    def __init__(self, attrs=None, format=None):
        super(DateInput, self).__init__(attrs)
        self.format = '%Y-%m-%d'

**Comment by gregmuellegger** [comment]
Hey, thanks for the input. It's actually not that obvious :) This originates from the work on #115. I've added a comment to the code to make clear why we are doing this: 53d1d8a8d7f00c14bdc6249afd9242ba1748fe3b
