### ISSUE TITLE
ClearableFileInput widget doesn't handle initial_text, input_text and clear_checkbox_label 

### ISSUE THREAD

**Issue by ghost** [gregmuellegger/django-floppyforms#169]
According to [the docs](http://django-floppyforms.readthedocs.org/en/latest/widgets-reference.html#floppyforms.widgets.ClearableFileInput) you should be able to override the mentioned attributes, however setting them has no effect.

This is what I've done

``` python
class CustomClearableFileInput(floppy.ClearableFileInput):
    """Override template on ClearableFileInput.
    """
    clear_checkbox_label = 'Remove custom cover'
```

but the output shows the default text. As far as I can see ClearableFileInput doesn't actually use these attributes, despite the documentation saying:

> The initial_text, input_text and clear_checkbox_label attributes are provided in the template context.

I've also tried:

```python
custom_background = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(
            attrs={
                'accept': ','.join(settings.ALLOWED_IMAGE_TYPES),
                'clear_checkbox_label': 'Remove custom cover'}
        ),
        validators=[image_format_validator]
    )
```

**Comment by gregmuellegger** [comment]
Hi, thanks for the report. I've added the labels as documented and released 1.6.2 that contains the fix.
