### ISSUE TITLE
I can't get static/admin/img/gis to serve

### ISSUE THREAD

**Issue by jeabraham** [gregmuellegger/django-floppyforms#171]
Arghh this is driving my crazy.  Everything works except I get this 404 error

     "GET /static/admin/img/gis/move_vertex_on.png HTTP/1.1" 404 1821

and a similar 404 error for move_vertex_off.png

Yet all the other admin static file images in /static/admin/img are served just fine, it's only the ones in the gis subdirectory that cause problems.  The files physically exist and permissions are ok, why might those files not get served?  How can I add the gis subfolder to static?  If I add it using 

    STATICFILES_DIRS = (
       os.path.join(PROJECT_DIR, "static", "admin", "img", "gis"),

then the files are available to be served out of the /static URL, but not out of /static/admin/img/gis URL where floppyforms is looking.

(ie. I can get http://0.0.0.0:8000/static/move_vertex_on.png to work by explicitly listing the directory, and all the regular admin images like http://0.0.0.0:8000/static/admin/img/icon-addlink.svg work because admin includes them, but no joy on getting the http://0.0.0.0:8000/static/admin/img/gis/move_vertex_on.png url working, which is what floppy  forms is expecting.)

Using django 1.9.4

**Comment by gregmuellegger** [comment]
It take me a while as well, but I figured the reason why this gets you an error is that the file is called move_vertex_on**.svg** in Django 1.9 …

I assume we have to account for that in django-floppyforms.

For now a workaround might be to overwrite the `floppyforms/gis/openlayers.html` and fix the url to the file there by hand.

I also tried to address the issue in the current master. It would be super cool if you could try out the master and see if it fixes your problem.

**Comment by jeabraham** [comment]
I didn't check out master (git still confuses me) but I changed the .html file directly and I don't get those errors in the log anymore.

Mind you, even with those errors gone, I cannot figure out how to remove a vertex from my polygon.

--
John Abraham
jea@hbaspecto.com
403-232-1060
