### ISSUE TITLE
Javascript check for input type 

### ISSUE THREAD

**Issue by rtpm** [gregmuellegger/django-floppyforms#26]
In datepicker example you are using " var type = $('<input type="date" />').attr('type');".

Chrome v.16 always returns "date" (as well as firefox). I'm using a "modernizr" library to check for support and it works fine.. maybe you could mention that in docs ?

There's still a mess with html5 browser support.

Thanks

**Comment by gregmuellegger** [comment]
Wow, long wait but we finally made it. Thanks for reporting! :)
