### ISSUE TITLE
Extra attributes to hidden fields are not parsed by default

### ISSUE THREAD

**Issue by jleclanche** [gregmuellegger/django-floppyforms#66]
This took me by surprise while porting an existing app to use floppyforms. All of a sudden, the input type="hidden" in my ModelForm no longer had any of their extra attributes

Slightly reduced code:

```
class HiddenMapInput(HiddenInput):
	def __init__(self, map, maptype, *args, **kwargs):
		kwargs.setdefault("attrs", {"data-map": map, "data-maptype": maptype})
		super(HiddenMapInput, self).__init__(*args, **kwargs)

class MerchantForm(ModelForm):
	class Meta:
		widgets = {
			"latitude": HiddenMapInput("merchant_coords", "latitude"),
		}
```

I tracked it down to templates/floppyforms/layouts/p.html, in the formconfig line for hidden fields. We then end up here in ```templates/floppyforms/rows/p.html```:
```{% block hidden_fields %}{% for field in hidden_fields %}{{ field.as_hidden }}{% endfor %}{% endblock %}```

This calls django.forms.BoundField.as_hidden(), which takes an attrs=None argument. So of course the extra attributes disappear here.

Switching to just ```{{ field }}``` fixes the issue but I'm not sure about the implications.

**Comment by gregmuellegger** [comment]
I see that this might be non-intuitive. But it is exactly the same behaviour that Django shows.

When using Django 1.7:
```python
>>> from django import forms
>>> class MyForm(forms.Form):
...     my_field = forms.CharField(widget=forms.HiddenInput(attrs={'ng-model': 'form.my_field'}))
...
...
>>> form = MyForm()
>>> print form['my_field']
<input id="id_my_field" name="my_field" ng-model="form.my_field" type="hidden" />
>>> print form['my_field'].as_hidden()
<input id="id_my_field" name="my_field" type="hidden" />
```

And when using django-floppyforms 1.3.0:
```
>>> import floppyforms as forms
>>> class MyForm(forms.Form):
...     my_field = forms.CharField(widget=forms.HiddenInput(attrs={'ng-model': 'form.my_field'}))
...
...
>>> form = MyForm()
>>> print form['my_field']
<input type="hidden" name="my_field" required ng-model="form.my_field" id="id_my_field">

>>> print form['my_field'].as_hidden()
<input type="hidden" name="my_field" id="id_my_field">
```

I think django-floppyforms should only replicate Django's behaviour as good
as possible. After all it is design as a drop-in replacement. So I'm sorry for
closing this as a won't-fix as I see your point.

Maybe that is something that you would like to address in Django core?
